include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    use_setters_to_change_properties: false
    non_constant_identifier_names: false
    file_names: false
    omit_local_variable_types: false
    constant_identifier_names: false
    one_member_abstracts: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    avoid_catches_without_on_clauses: false
    prefer_mixin: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "lib/packages/**"
  errors:
    missing_required_param: error
    missing_return: error