name: teste_caique_marvel_app
description: Projeto em flutter apresentando informações das histórias em quadrinhos da marvel, realizado como teste técnico para desenvolvedor flutter na SoftDesign.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  dio: ^5.3.3
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  skeleton_text: ^3.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
